# Generated by Django 5.2.7 on 2025-10-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-15 12:00:00'),
            preserve_default=False,
        ),
    ]
